version: '3'

services:

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - db_vol:/var/lib/postgresql/data 
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: 'npm run dev'
    ports:
      - "3001:3001"
    volumes:
      - ./:/api
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - api-network


volumes:
  db_vol:

networks:
  api-network:
    driver: bridge